# Generated by Django 4.0.4 on 2022-05-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('gpa', models.FloatField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('level', models.CharField(choices=[('level 1', 'level 1'), ('level 2', 'level 2'), ('level 3', 'level 3'), ('level 4', 'level 4')], max_length=7)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
