# Generated by Django 4.0.4 on 2022-05-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
