# Generated by Django 4.0.4 on 2022-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CourseCode', models.CharField(max_length=20)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDescription', models.CharField(max_length=500)),
                ('CourseHours', models.IntegerField()),
                ('CourseCategory', models.CharField(max_length=20)),
                ('CourseInsructors', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Id'],
            },
        ),
    ]
