# Generated by Django 4.0.4 on 2022-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseCode',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseHours',
            new_name='Hours',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseInsructors',
            new_name='Insructors',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseCategory',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseDescription',
        ),
        migrations.AddField(
            model_name='course',
            name='Category',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
