# Generated by Django 4.0.4 on 2022-08-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_coursecode_course_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['Code']},
        ),
    ]
